### ISSUE TITLE
Query never completes

### ISSUE THREAD

**Issue by RadxaYuntian** [devmount/third-stats#445]
**Describe the bug**

Similar to #19, the Mails total number stopped increasing and the progress bar is full. But the spinning wheel is still going and the graph is never shown on the page.

**To Reproduce**

1. Open stat page

**Expected behavior**

Data collection ends in reasonable amount of time with graphs.

**Screenshots**

![Image](https://github.com/user-attachments/assets/8c7cc8a7-bc79-4e3c-a0be-48e86c9ebe87)

**System (please complete the following information):**

- OS: Arch Linux (updated today)
- Thunderbird Version: 128.5.2esr (64-bit)

**Additional context**

**Comment by devmount** [comment]
Thank you for this report! Can you please [check the console](https://github.com/devmount/third-stats/issues/19#issuecomment-701991021) if there are any errors thrown during the data processing?

**Comment by RadxaYuntian** [comment]
So one thing I'm not sure if you are aware is that there are 2 ThirdStats entries in the Debug menu. One listed under Tabs (since I do have the stat tab open and waiting for it to return), and one under Extensions. I tried a few commands in both and neither get me anything similar to what other people were posting, so I refrained posting this detail in the original report.

Can you tell me which context should I inspect into?

**Comment by RadxaYuntian** [comment]
No worries. I can check there.

Here is the Tabs entry:

![Image](https://github.com/user-attachments/assets/5ada4bb1-2e26-4759-9a58-172c9e285558)

**Comment by RadxaYuntian** [comment]
There is no error message when it reached this final state:

![Image](https://github.com/user-attachments/assets/4344b3e0-fbdd-4190-8211-52245538a642)

**Comment by devmount** [comment]
That is unfortunate, that there is no output at all. I'll work on a debug mode for ThirdStats (#447) to provide some more information, were the processing is stuck. Once that landed, you can test again and have some (hopefully) more useful information.

**Comment by devmount** [comment]
I implemented the debug mode now and released ThirdStats 1.12.0 - you can wait until its approved on ATN or download the XPI file from the release and install it manually. Let me know if that was helpful in any way.

**Comment by RadxaYuntian** [comment]
This is the final state:

![Image](https://github.com/user-attachments/assets/08832c6c-df21-48aa-974d-0012305cde2d)

Is it possible for a folder to contain a link to its ancestors? Since the stats (and the debug log) is only updated when a folder is counted, I feel the thread is stuck in an infinite loop.

It looks flat on my TB here, but I had misclicks before where some folders were moved under another folder, which I moved out later:

![Image](https://github.com/user-attachments/assets/27a55ef6-ef62-4869-b9dc-65e3c6ad6105)

It is also flat in my mail provider's web UI:

![Image](https://github.com/user-attachments/assets/ec14f599-a332-4d91-876d-56b54943841b)

**Comment by devmount** [comment]
> Is it possible for a folder to contain a link to its ancestors? Since the stats (and the debug log) is only updated when a folder is counted, I feel the thread is stuck in an infinite loop.

No, this shouldn't be possible. Looks more like there is an issue in your `linux-netdev` folder which leaves Thunderbird / ThirdStats stuck while processing.

Since we have a similar issue with #451 now: Do you have errors in your console, if you open the add-on popup (when on the main Thunderbird page, click the small ThirdStats icon on the top right)?

**Comment by RadxaYuntian** [comment]
No error here:

![Image](https://github.com/user-attachments/assets/ce22e709-5726-4edf-9f36-8154f264f1d2)

**Comment by devmount** [comment]
Ok, it might have something to do with special folders in Thunderbird. I released ThirdStats 1.12.1 which contains a fix to exclude all virtual folders  from processing. Once it is approved on ATN please test if this changes anything on this issue.

**Comment by RadxaYuntian** [comment]
Seems to be the same as before. I'll let this run over the weekend to see if that changes anything.

![Image](https://github.com/user-attachments/assets/2d36e319-7a22-4860-b31d-2e1931d95e2a)

**Comment by RadxaYuntian** [comment]
I forgot about this and rebooted my machine today. Luckily I have TB in autostart, and it reopened ThirdStats as the previously opened tab. This has been running over 1 hour now and it is still not finished. Basically the above screenshot sans a few more mails during the weekend.

**Comment by devmount** [comment]
Ok. Looks like I really need to think of a way to extend the debug mode. Like not only outputting stuff to the console, but more like running a test suite with some more useful information (folders or messages that cannot be processed for whatever reason) nicely shown in the add-on options (or a dedicated debug page). Created #462 for that.

And I should implement a timeout for folder processing. Like the processing of one single folder should never exceed e.g. 2 minutes. I have a folder having alone 16k messages, which only take a few seconds to process (on a mediocre laptop with an i5). This way, the processing should at least come to end and results should be shown to you, even if there might be messages or folders excluded for some reason. Created #463 for that.

But I also want to transparently set expectations here that those things take time to implement, which I only have so much available next to family and work 😇

**Comment by Tamura-Teika** [comment]
I'm reporting this issue because I'm loading 11.36 million messages and calculating statistics.
My environment is Windows 11, Thunderbird 143.0.1, and ThirdStats 1.12.1.
The debug message is as follows:

TypeError: can't access property Symbol.iterator, Startup.KeyShortcuts is undefined

Stacktrace
_addWindowHostShortcuts@resource://devtools/client/framework/toolbox.js:1388:24
_addChromeEventHandlerEvents@resource://devtools/client/framework/toolbox.js:1210:10
open@resource://devtools/client/framework/toolbox.js:1029:12

**Comment by devmount** [comment]
@Tamura-Teika Thanks for your report. I created #478 for it to keep this thread related to @RadxaYuntian's issue.

**Comment by devmount** [comment]
@RadxaYuntian Is this still happening on your end?

**Comment by RadxaYuntian** [comment]
<img width="1869" height="528" alt="Image" src="https://github.com/user-attachments/assets/2cf1ba16-c8be-49f5-bb36-560c18c7e2f1" />

Yeah the statistic is still going after 4 hours.

**Comment by devmount** [comment]
Ok thank you for confirming! If you enable debug mode in the ThirdStats settings, open the console and run the stats processing again, does it stop at a specific folder?

Make sure to open the console on the stats page (<kbd>CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>I</kbd>).

**Comment by RadxaYuntian** [comment]
<img width="1804" height="1299" alt="Image" src="https://github.com/user-attachments/assets/37f3caae-fdcc-402f-9c03-7d4f3876dad1" />

It stuck at /INBOX at the end.

**Comment by devmount** [comment]
How many messages are in Inbox actually? Is the number shown in the console correct?

**Comment by RadxaYuntian** [comment]
In the property it currently reads as 79944. Probably because I received a few more after ThirdStats got stuck. There is a repair folder button so I'm trying that now.

**Comment by devmount** [comment]
ThirdStats (unfortunately) only logs folders that are complete, so I think the Inbox folder is fine. It's another folder that is stuck. Let me check what options we have here.

**Comment by devmount** [comment]
Ok I created a beta of the next ThirdStats version logging each page call to the console:

[third-stats_v1.12.5-beta.zip](https://github.com/user-attachments/files/30339662/third-stats_v1.12.5-beta.zip)

Extract the xpi file from the zip somewhere. Then in Thunderbird go to Extensions > Cog Icon > Debug add-ons > Button: Load temporary add-on > Select the xpi file. Make sure ThirdStats still has the debug mode enabled, clean the console and start processing again. There should be lots of log entries now informing about the pages being processed.

I also added a hard timeout of 30s per page, so processing should eventually come to an end this time 🙏🏻

**Comment by RadxaYuntian** [comment]
Repair folder is still going and it only processed 32K emails so far. I'll try the debug build next Monday.

**Comment by devmount** [comment]
Alright. Let me know if there's any news and have a nice weekend!

**Comment by RadxaYuntian** [comment]
<img width="1806" height="1770" alt="Image" src="https://github.com/user-attachments/assets/4905ac97-9ea2-495e-b04a-420adb96555d" />

The debug build actually completed the statistic. I guess the issue is in `linux-netdev` folder so I'll try clearing it.

**Comment by RadxaYuntian** [comment]
With the folder purged I can now complete statistic on 1.12.4 as well.

**Comment by devmount** [comment]
That's great news! Thanks so much for testing and staying with me on this. Sorry this took 1.5 years to figure out 😅 I plan to release the next ThirdStats version in the upcoming days, the advanced debug output will be part of it. Is there anything more to this issue or can we close it?

**Comment by devmount** [comment]
I filed #462 to have a more user-friendly debug output, since not everyone wants to open consoles and look at log entries. When this is implemented, we could even list the exact message causing the issue.

**Comment by RadxaYuntian** [comment]
I think we can close this. Whatever caused the blocking was already fixed in the 1.12.5 debug build, so the same issue should not occur again in the future.
